// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGbq27e0m3832qrQgetTHci2uKcPzSWiY',
    appId: '1:216964166409:web:2d3bd80b618f74a1dc59d8',
    messagingSenderId: '216964166409',
    projectId: 'college-project-74d8a',
    authDomain: 'college-project-74d8a.firebaseapp.com',
    storageBucket: 'college-project-74d8a.appspot.com',
    measurementId: 'G-CFV9HWZ495',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMkXaHmpbZ1ZffND6ruuBOFIzArN8AUnk',
    appId: '1:216964166409:android:4065a3ec00d1045fdc59d8',
    messagingSenderId: '216964166409',
    projectId: 'college-project-74d8a',
    storageBucket: 'college-project-74d8a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBP763l54_xV0D6xeibngR0VfUK7yuFVZ0',
    appId: '1:216964166409:ios:b117a31c0f7135eedc59d8',
    messagingSenderId: '216964166409',
    projectId: 'college-project-74d8a',
    storageBucket: 'college-project-74d8a.appspot.com',
    iosBundleId: 'com.example.collegeProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBP763l54_xV0D6xeibngR0VfUK7yuFVZ0',
    appId: '1:216964166409:ios:0718ec4ead4378d0dc59d8',
    messagingSenderId: '216964166409',
    projectId: 'college-project-74d8a',
    storageBucket: 'college-project-74d8a.appspot.com',
    iosBundleId: 'com.example.collegeProject.RunnerTests',
  );
}
